import esbuild from 'esbuild';
import process from 'process';

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	entryPoints: ['main.ts'],
	bundle: true,
	external: ['obsidian', 'child_process'],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	platform: 'node',
	banner: {
		js: '/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */',
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
